### ISSUE TITLE
Add iptables to konga container

### ISSUE THREAD

**Issue by harishanand95** [rbccps-iisc/ideam#12]
* Block all traffic from Konga container to outside. 
* Allow Konga to communicate only with Kong container.

**Comment by pct960** [comment]
Konga container now only listens to localhost. So, iptables is not needed. If Konga is needed remotely then SSH port forwarding can be used.

**Comment by pct960** [comment]
This was done in https://github.com/rbccps-iisc/ideam/pull/144
