### ISSUE TITLE
Re-installation contains old data

### ISSUE THREAD

**Issue by swaminathanvasanth** [rbccps-iisc/ideam#145]
Eg. Catalog data is persisted even after re-installation

**Comment by harishanand95** [comment]
It might be helpful if we try reinstall in travis. Travis tests will have old data persisted.

https://github.com/rbccps-iisc/ideam/blob/d02df863a91d15f29bacc667c2593709f251aea8/ideam.py#L77

**Comment by pct960** [comment]
Fixed in https://github.com/rbccps-iisc/ideam/pull/156
