### ISSUE TITLE
Lets use Shell=False everywhere

### ISSUE THREAD

**Issue by arun-babu** [rbccps-iisc/ideam#158]

**Comment by pct960** [comment]
Ok, I'll do that as soon as possible.

**Comment by pct960** [comment]
Tried doing it. Apparently, it requires the commands to be split up. Since ``share.py`` is a makeshift arrangement and the LDAP commands are very complex, I think we can skip it for now.

**Comment by harishanand95** [comment]
https://docs.python.org/2/library/subprocess.html#frequently-used-arguments 
Saw that, sorry about that! 😅
