### ISSUE TITLE
publish:Previously published messages are not displayed.

### ISSUE THREAD

**Issue by gayatri678** [rbccps-iisc/ideam#180]

**Comment by pct960** [comment]
This cannot be allowed as the data lease time begins from the moment the share request is approved. Therefore, access to previously published data cannot be granted

**Comment by gayatri678** [comment]
I do deny your point on the following grounds:
Imagine a situation when live streaming is going on .
Streamer publishes data and shares it to receivers whoever are subscribed to it.
Chats and comments have occured.
If a new user subscribes for the data, he is having the authority to view the previous comments and all.
Considering VOD, the viewer should be able view the video as well as chats.
