### ISSUE TITLE
Pushpin fails when started in screen or supervisor

### ISSUE THREAD

**Issue by harishanand95** [rbccps-iisc/ideam#50]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

### Middleware version the issue has been seen with
> ideam v1.0.0 latest 

### Bug report
Pushpin fails when started in screen or supervisor which results in landing page not shown.

**Comment by harishanand95** [comment]
@swaminathanvasanth does starting pushpin in tmux fix the issue?

**Comment by harishanand95** [comment]
Fixed in PR #54

**Comment by swaminathanvasanth** [comment]
Pushpin in tmux fixed the issue.
