### ISSUE TITLE
Auto-Start Failure

### ISSUE THREAD

**Issue by swaminathanvasanth** [rbccps-iisc/ideam#60]
Observed pushpin and catalogue server auto-start failure after docker restart.

**Comment by pct960** [comment]
Can we use supervisor for running ``npm start`` in the background?

**Comment by harishanand95** [comment]
I have tried that.. it didn't work for some reason.

**Comment by harishanand95** [comment]
Currently we have opted to use `tmux` over `screen` to start both of these servers inside the containers. 
I'm closing this issue as we haven't observed this issue for a while.
If it's found again, we can reopen this issue and figure out a fix.
