### ISSUE TITLE
/follow and /share APIs stop working

### ISSUE THREAD

**Issue by pct960** [rbccps-iisc/ideam#67]
The ``/follow`` and ``/share`` APIs do not work from time to time although ``supervisor`` is running in the background. A manual intervention is required everytime this happens.

**Comment by pct960** [comment]
Furthermore, this issue is caused even when ``share.py`` is running in the background. I understand that ``supervisor`` manages the process, but there is some sort of inherent disconnect between ``supervisor`` and the ``share.py`` file. Could this also be something due to ``japronto``?

**Comment by harishanand95** [comment]
we require more logs to diagnose this issue

**Comment by pct960** [comment]
Has using ``tmux`` solved the issue?

**Comment by harishanand95** [comment]
yeah. I will close this issue now. If there are further reports of failure, then we can reopen this issue.
